version: "3.8"

services:
  apigateway:
    build:
      context: ./apiGatway
      dockerfile: Dockerfile
    image: wassim/apigateway
    ports:
      - "1300:1300"
    networks:
      - my-network

  authentication:
    build:
      context: ./userService/
      dockerfile: Dockerfile
    image: wassim/authentication
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    networks:
      - my-network

  products:
    build:
      context: ./productsService/
      dockerfile: Dockerfile
    image: wassim/products
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
